---
name: 'lint'

on: [push, pull_request]

jobs:
  markdown-lint:
    name: markdown-lint
    runs-on: ubuntu-20.04
    steps:
      - name: Clone
        uses: actions/checkout@v2
      - name: Run markdown-lint
        uses: avto-dev/markdown-lint@6e6d4393411fbaae3c3aeee5661ba84a0352ed3b
        # v1.4.0 => 6e6d4393411fbaae3c3aeee5661ba84a0352ed3b
        with:
          config: '.github/linters/.markdown-lint.yml'
          args: './README.md'
